version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      bash -c "/myapp-miguchi/wait-for-it.sh db:3306 --timeout=30 --strict -- 
      bundle exec rails db:create &&
      bundle exec unicorn -p 3000 -c /myapp-miguchi/config/unicorn.rb"
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp-miguchi' #任意のアプリ名
      - tmp-data:/myapp-miguchi/tmp/sockets #ソケット通信用ファイルをnginxコンテナと共有
      - public-data:/myapp-miguchi/public #画像データなどをnginxと共有
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db

  db:
    platform: linux/x86_64 #M1チップ対応のため追記
    restart: always
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/myapp-miguchi/tmp/sockets
      - public-data:/myapp-miguchi/public
    depends_on:
      - web 

volumes:
  mysql-data:
  tmp-data:
  public-data: